//* This file is explicitly licensed under the MIT license. *//
//* Copyright (c) 2026 Citadel Station Developers           *//

/**
 * Runs multiple generator cycles on a buffer.
 */
/datum/jigsaw_chain_generator_config
	var/prepared = FALSE

	/**
	 * Tile budget.
	 * * Overrules [tile_budget_ratio] if set.
	 * * Limits the total number of tiles generated by the chain-generation.
	 */
	var/tile_budget
	/**
	 * Tile budget as a ratio of available tiles.
	 * * Limits the total number of tiles generated by the chain-generation.
	 */
	var/tile_budget_ratio
	/**
	 * Custom budgets, key-value list of string-number.
	 * * This is applied in parallel with the existing generator config budgets, so
	 *   if this is lower, this is applied instead of that.
	 */
	var/list/custom_budgets = list()

	/**
	 * A list of generator config-literals to use.
	 * * Associate to number for weight. None = 1 weight.
	 */
	var/list/datum/jigsaw_generator_config/configs = list()

	/**
	 * A list of resolvables for presets to use.
	 * * Associate to number for weight. None = 1 weight.
	 */
	var/list/datum/prototype/jigsaw_generator_preset/presets = list()

/datum/jigsaw_chain_generator_config/proc/prepare()
	SHOULD_NOT_OVERRIDE(TRUE)

	if(prepared)
		return
	prepared = TRUE
	prepare_impl()

/datum/jigsaw_chain_generator_config/proc/prepare_impl()
	PROTECTED_PROC(TRUE)

/datum/jigsaw_chain_generator_config/proc/get_generator_configs() as /list
	SHOULD_CALL_PARENT(TRUE)
	prepare()

	var/list/datum/jigsaw_generator_config/generator_configs = list()

	for(var/datum/jigsaw_generator_config/config in configs)
		generator_configs += config

	for(var/datum/prototype/jigsaw_generator_preset/preset in presets)
		generator_configs += preset.get_config()

	return generator_configs

/datum/jigsaw_chain_generator_config/weighted_pick

/datum/jigsaw_chain_generator_config/literally_everything

/datum/jigsaw_chain_generator_config/literally_everything/get_generator_configs()
	var/list/datum/jigsaw_generator_config/generator_configs = list()

	for(var/datum/jigsaw_generator_config/config in configs)
		generator_configs += config

	for(var/datum/prototype/jigsaw_generator_preset/preset in presets)
		generator_configs += preset.get_config()

	return generator_configs


/datum/jigsaw_chain_generator_config
