//* This file is explicitly licensed under the MIT license. *//
//* Copyright (c) 2026 Citadel Station Developers           *//

/datum/jigsaw_chain_generator_resultant_config
	/**
	 * Tile budget.
	 * * Overrules [tile_budget_ratio] if set.
	 * * Limits the total number of tiles generated by the chain-generation.
	 */
	var/tile_budget
	/**
	 * Tile budget as a ratio of available tiles.
	 * * Limits the total number of tiles generated by the chain-generation.
	 */
	var/tile_budget_ratio
	/**
	 * Custom budgets, key-value list of string-number.
	 * * This is applied in parallel with the existing generator config budgets, so
	 *   if this is lower, this is applied instead of that.
	 */
	var/list/custom_budgets = list()

	/**
	 * A list of generator config-literals to use until out of budget or time expired.
	 * * Associate to number for weight. None = 1 weight.
	 * * This list should be read only for its contents, because configs might be
	 *   directly linked in.
	 */
	var/list/datum/jigsaw_generator_config/configs = list()

/datum/jigsaw_chain_generator_resultant_config/Destroy()
	configs = null
	return ..()
