//* This file is explicitly licensed under the MIT license. *//
//* Copyright (c) 2023 Citadel Station developers.          *//

//* nightshift flags

#define NIGHTSHIFT_LEVEL_UNSET (1<<0)

#define NIGHTSHIFT_LEVEL_PUBLIC_HALLWAYS (1<<1)
#define NIGHTSHIFT_LEVEL_PUBLIC_FACILITIES (1<<2)

#define NIGHTSHIFT_LEVEL_DEPARTMENT_HALLWAYS (1<<3)
#define NIGHTSHIFT_LEVEL_DEPARTMENT_FACILITIES (1<<4)
#define NIGHTSHIFT_LEVEL_DEPARTMENT_SENSITIVE (1<<5)
#define NIGHTSHIFT_LEVEL_DEPARTMENT_LEISURE (1<<6)

#define NIGHTSHIFT_LEVEL_COMMAND_HALLWAYS (1<<7)
#define NIGHTSHIFT_LEVEL_COMMAND_FACILITIES (1<<8)
#define NIGHTSHIFT_LEVEL_COMMAND_SENSITIVE (1<<9)

//* Do not randomly change this, it is used for configuration. *//
DEFINE_BITFIELD(nightshift_level, list(
	BITFIELD_NEW("Unset", NIGHTSHIFT_LEVEL_UNSET),
	BITFIELD_NEW("PublicHalls", NIGHTSHIFT_LEVEL_PUBLIC_HALLWAYS),
	BITFIELD_NEW("PublicAreas", NIGHTSHIFT_LEVEL_PUBLIC_FACILITIES),
	BITFIELD_NEW("DepartmentHalls", NIGHTSHIFT_LEVEL_DEPARTMENT_HALLWAYS),
	BITFIELD_NEW("DepartmentAreas", NIGHTSHIFT_LEVEL_DEPARTMENT_FACILITIES),
	BITFIELD_NEW("DepartmentSecure", NIGHTSHIFT_LEVEL_DEPARTMENT_SENSITIVE),
	BITFIELD_NEW("DepartmentLeisure", NIGHTSHIFT_LEVEL_DEPARTMENT_LEISURE),
	BITFIELD_NEW("CommandHalls", NIGHTSHIFT_LEVEL_COMMAND_HALLWAYS),
	BITFIELD_NEW("CommandAreas", NIGHTSHIFT_LEVEL_COMMAND_FACILITIES),
	BITFIELD_NEW("CommandSecure", NIGHTSHIFT_LEVEL_COMMAND_SENSITIVE),
))
